apiVersion: v1
kind: Service
metadata:
  name: resume-webpage-service
spec:
  selector:
    app: resume-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
