---
- hosts: localhost
  tasks:
    - name: Create namespace argocd
      shell: kubectl create namespace argocd

    - name: Install ArgoCD
      shell: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Change ArgoCD server service type to LoadBalancer
      shell: |
        kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
