name: AKS Deploy and Delete

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        default: 'Deploy-Azure-VM'
        type: choice
        options:
          - Deploy-Azure-VM
          - Delete-Azure-VM
          - Both

jobs:
  Deploy-Azure-AKS:
    if: ${{ github.event.inputs.action == 'Deploy-Azure-VM' || github.event.inputs.action == 'Both' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy Azure AKS
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: satha-pc
          template: ./windows-vm/aks_template.json
          parameters: ./windows-vm/aks_parameters.json
          deploymentName: DiskCreation



  Delete-Azure-AKS:
    if: ${{ github.event.inputs.action == 'Delete-Azure-VM' || github.event.inputs.action == 'Both' }}
    runs-on: ubuntu-latest
    needs: Deploy-Azure-AKS
    environment: delete-approval
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Delete Deployed Resources
        run: |
          az resource delete --resource-group satha-pc --name satha-windows-vm --resource-type Microsoft.Compute/virtualMachines
          
