name: AKS Deploy and Delete

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to perform'
        required: true
        default: 'Deploy-Azure-AKS'
        type: choice
        options:
          - Deploy-Azure-AKS
          - Delete-Azure-AKS
          - Both

jobs:
  Deploy-Azure-AKS:
    if: ${{ github.event.inputs.action == 'Deploy-Azure-AKS' || github.event.inputs.action == 'Both' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        id: vars
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sourcecode
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-image:${{ env.BUILD_NUMBER }}
